import darkJson from './dark.json';
import lightJson from './light.json';
import schema from './schema.json';
import { applyTheme, applyThemeIsolated } from './theme';
import { Theme } from './theme.type';
export * from './theme.type';
export { schema };
export const dark = darkJson as Theme;
export const light = lightJson as Theme;
export { ThemeCache } from './theme-cache';
export { ThemeProvider, useTheme } from './theme-context';
export type { ThemeDiscoveryFunction } from './theme-context';
export { ThemeLoader } from './theme-loader';
export { applyTheme, applyThemeIsolated };
